daq-2.0.6.tar.gz:
  size: 514687
  object_id: 6b26a6db-c902-4369-563d-d9decb9d367e
  sha: ec0ebfcd4568a3e4e58c774982c808c414dd71bc
golang1.6/go1.6.linux-amd64.tar.gz:
  size: 84799480
  object_id: f17062a0-6a34-4d6c-5123-33ce7404189e
  sha: 01a6a28dbe31a53103b600979bbbbd63a8104456
libdnet-1.12.tar.gz:
  size: 959945
  object_id: 501e3f27-b005-460a-6670-cb65e512ef75
  sha: 3ce046cde6e1872ccef3920923a768e6556b4cde
libpcap-1.7.4.tar.gz:
  size: 663021
  object_id: 80e5a9ef-60e9-4f42-6326-e02814a917cb
  sha: 3f31a7706c1487fca36b8379e511965a8d7cbd70
pcre-8.38.tar.gz:
  size: 2053336
  object_id: 0b52288a-54a6-4fde-4dd9-c77b76e4282b
  sha: 3ab418d0026c2a4e693ec783bd60660debc32b8f
snort-2.9.9.0.tar.gz:
  size: 6364482
  object_id: e77ac4c2-8381-418b-61ff-cff05c8313ca
  sha: c522b6130655e0d12299af6fd1a613b20259b4e3
snort-conf.tar.gz:
  size: 296234
  object_id: 9ef217a8-c0b6-4031-6426-c0645b64cd43
  sha: b49c882aaaa09d88779e1d7d5b58983f5615d89c
